<a href="https://colab.research.google.com/github/tonycota/deep-learning-challenge/blob/main/deep_learning_challenge_initial_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
columns_to_drop = ['EIN', 'NAME']
application_df.drop(columns=columns_to_drop, inplace=True)
application_df.head(10)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0

In [3]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
print(application_df.value_counts())

APPLICATION_TYPE  AFFILIATION       CLASSIFICATION  USE_CASE      ORGANIZATION  STATUS  INCOME_AMT     SPECIAL_CONSIDERATIONS  ASK_AMT   IS_SUCCESSFUL
T3                Independent       C1000           Preservation  Trust         1       0              N                       5000      1                3507
                  CompanySponsored  C1000           Preservation  Trust         1       0              N                       5000      0                1379
                                    C1200           Preservation  Association   1       0              N                       5000      0                1122
                  Independent       C1000           Preservation  Trust         1       0              N                       5000      0                1102
                                    C1200           Preservation  Trust         1       0              N                       5000      1                1052
                                                                                                                                                          ...
                                    C1000           Preservation  Trust         1       100000-499999  N                       140853    1                   1
                                                                                                                               140864    1                   1
                                                                                                                               140938    1                   1
                                                                                                                               140950    1                   1
T9                National          C1000           ProductDev    Co-operative  1       10M-50M        N                       42312554  1                   1
Name: count, Length: 9622, dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_counts = application_df["APPLICATION_TYPE"].value_counts()
app_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classy_counts = application_df["CLASSIFICATION"].value_counts()
classy_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
helpful_classy_counts = classy_counts.loc[classy_counts > 1]
helpful_classy_counts[:15]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: count, dtype: int64

In [11]:
classifications_to_replace = list(classy_counts[classy_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classy_counts[classy_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
app_numeric = pd.get_dummies(application_df)
app_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [14]:
# Split our preprocessed data into our features and target arrays
X = app_numeric.drop('IS_SUCCESSFUL', axis=1)
y = app_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

# Create the neural network
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 352

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 403 (1.57 KB)
Trainable params: 403 (1.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6429 - accuracy: 0.6637
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5717 - accuracy: 0.7204
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5641 - accuracy: 0.7264
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5608 - accuracy: 0.7283
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5588 - accuracy: 0.7292
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7289
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7298
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5550 - accuracy: 0.7299
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7306
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7294
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7308
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7304
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7307
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7301
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7314
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7304
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7302
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7302
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7304
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7297
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7313
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7315
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7313
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7313
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7313
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7316
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7329
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5472 - accuracy: 0.7323
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7332
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7329
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7316
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7320
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7324
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7316
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7315
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7321
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7325
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7333
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7320
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7323
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7318
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7324
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7322
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7329
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7317
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7321
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7325
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7326
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7327
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7325
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7327
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7327
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7336
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7333
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7328
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7330
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7333
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7331
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7321
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7330
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7330
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7339
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7332
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7329
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7332
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7337
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7327
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7334
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7340
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7337
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7333
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7328
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7346
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7327
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7339
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7336
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7336
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7338
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7338
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7342
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7332
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7344
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7340
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7330
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7337
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7338
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7345
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7334
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7345
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7339
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7345
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7333
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7341
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7325
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7344
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7340
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7333
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7338
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7340
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7343

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5563 - accuracy: 0.7279 - 474ms/epoch - 2ms/step
Loss: 0.5563145279884338, Accuracy: 0.7279300093650818

In [23]:
# Export our model to HDF5 file
# import os dependency
import os
desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
file_path = os.path.join(desktop_path, "AlphabetSoupCharity.h5")
nn.save(file_path)

# save file from google colab
from google.colab import files
files.download(file_path)
# Ensure file was saved into correct directory
print(f"Model saved to {file_path}")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

Model saved to /root/Desktop/AlphabetSoupCharity.h5